<template><h1 id="缓存" tabindex="-1"><a class="header-anchor" href="#缓存" aria-hidden="true">#</a> 缓存</h1>
<p>缓存工具库是对浏览器api: sessionStorage, localStorage的封装, 使其更加易用简单.</p>
<h2 id="快速使用" tabindex="-1"><a class="header-anchor" href="#快速使用" aria-hidden="true">#</a> 快速使用</h2>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> WebCache <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'fe-sdk'</span>

<span class="token comment">// 获取对键的类型提示</span>
<span class="token keyword">type</span> <span class="token class-name">SessionKeys</span> <span class="token operator">=</span> <span class="token string">'TOKEN'</span> <span class="token operator">|</span> <span class="token string">'USER'</span>

<span class="token keyword">type</span> <span class="token class-name">LocalKeys</span> <span class="token operator">=</span> <span class="token string">'THEME'</span>

<span class="token keyword">const</span> session <span class="token operator">=</span> WebCache<span class="token punctuation">.</span><span class="token generic-function"><span class="token function">create</span><span class="token generic class-name"><span class="token operator">&lt;</span>SessionKeys<span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token string">'session'</span><span class="token punctuation">)</span>
<span class="token keyword">const</span> local <span class="token operator">=</span> WebCache<span class="token punctuation">.</span><span class="token generic-function"><span class="token function">create</span><span class="token generic class-name"><span class="token operator">&lt;</span>LocalKeys<span class="token operator">></span></span></span><span class="token punctuation">(</span><span class="token string">'local'</span><span class="token punctuation">)</span>

session<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'TOKEN'</span><span class="token punctuation">,</span> <span class="token string">'token'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h2 id="设置过期时间" tabindex="-1"><a class="header-anchor" href="#设置过期时间" aria-hidden="true">#</a> 设置过期时间</h2>
<p>业务中通常会有使用token进行授权的方式, 这时候token需要保存到前端, 以前的做法是在浏览器cookie中保存这些参数, 但是cookie有一个最大的缺点, 那就是存储长度限制, 但cookie也有其有点, 那就是可以通过过期时间来消除cookie. 因此在storage缓存中引入了过期时间的参数.</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token comment">// 这里的3600是以秒为单位, 表示3600秒之后这条数据过期</span>
local<span class="token punctuation">.</span><span class="token function">set</span><span class="token punctuation">(</span><span class="token string">'TOKEN'</span><span class="token punctuation">,</span> <span class="token string">'my token'</span><span class="token punctuation">,</span> <span class="token number">3600</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h2 id="批量获取" tabindex="-1"><a class="header-anchor" href="#批量获取" aria-hidden="true">#</a> 批量获取</h2>
<p>当有需要是可以通过批量操作使代码看起来更加简洁</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code>session<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'TOKEN'</span><span class="token punctuation">,</span> <span class="token string">'USER'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h2 id="获取时给一个默认值" tabindex="-1"><a class="header-anchor" href="#获取时给一个默认值" aria-hidden="true">#</a> 获取时给一个默认值</h2>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code>session<span class="token punctuation">.</span><span class="token function">get</span><span class="token punctuation">(</span><span class="token string">'TOKEN'</span><span class="token punctuation">,</span> <span class="token string">'TOKEN'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br></div></div><h2 id="移除" tabindex="-1"><a class="header-anchor" href="#移除" aria-hidden="true">#</a> 移除</h2>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token comment">// 移除单个</span>
session<span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span><span class="token string">'TOKEN'</span><span class="token punctuation">)</span>

<span class="token comment">// 移除多个</span>
session<span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span><span class="token punctuation">[</span><span class="token string">'TOKEN'</span><span class="token punctuation">,</span> <span class="token string">'USER'</span><span class="token punctuation">]</span><span class="token punctuation">)</span>

<span class="token comment">// 清空</span>
session<span class="token punctuation">.</span><span class="token function">remove</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br></div></div><h2 id="添加事件" tabindex="-1"><a class="header-anchor" href="#添加事件" aria-hidden="true">#</a> 添加事件</h2>
<p>有时候你可能需要在设置缓存的时候执行一些操作, 可以使用on方法来添加事件</p>
<div class="language-typescript ext-ts line-numbers-mode"><pre v-pre class="language-typescript"><code><span class="token comment">// 添加一个叫做log的事件</span>
session<span class="token punctuation">.</span><span class="token function">on</span><span class="token punctuation">(</span><span class="token string">'log'</span><span class="token punctuation">,</span> <span class="token punctuation">(</span>key<span class="token punctuation">,</span> value<span class="token punctuation">,</span> temp<span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token builtin">console</span><span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">Date</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">toLocaleString</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">设置了</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>key<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">为</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>value<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>

<span class="token comment">// 移除事件</span>
session<span class="token punctuation">.</span><span class="token function">off</span><span class="token punctuation">(</span><span class="token string">'log'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div></template>
