name: docs

on:
  # push到main分支时触发
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      # 使用nodejs 16版本
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      # 缓存 node_modules
      # - name: Cache dependencies
      #   uses: actions/cache@v2
      #   id: yarn-cache
      #   with:
      #     path: |
      #       **/node_modules
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      # 如果缓存没有命中，安装依赖
      # - name: Install dependencies
      #   if: steps.yarn-cache.outputs.cache-hit != 'true'
      #   run: yarn --frozen-lockfile
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest
          run_install: true

      # 运行构建脚本
      - name: Build
        run: pnpm docs:build

      # 部署
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACT }}


