name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: DeployDocs
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACT }}
        TARGET_REPO: wenhongjie/fe-dk
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: |
          npm i -g pnpm
          pnpm i && pnpm docs:build

        BUILD_DIR: docs/.vuepress/dist